name: Build Deploy on Environment
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy to. One of [qa, test]'
        default: 'test'
        required: true
        type: string

jobs:
  build-deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY }}
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
      KUBE_CONFIG_DATA:  ${{ secrets.KUBE_CONFIG_DATA }}
      ENVIRONMENT_NAME: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    name: Build Deploy
    environment:
      name: ${{ inputs.environment }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      env:
        ENVIRONMENT_NAME: ${{ inputs.environment }}
      run: |
        echo DOCKER_ENV_TAG=${ENVIRONMENT_NAME}-$GITHUB_SHA >> $GITHUB_ENV
        cat ".github/env.common" >>$GITHUB_ENV
        cat ".github/env.${ENVIRONMENT_NAME}" >>$GITHUB_ENV

    - name: Build
      uses: ./.github/actions/build

    - name: Docker Build Publish
      uses: ./.github/actions/docker-build-publish

    - name: helm deploy
      uses: koslib/helm-eks-action@v1.8.0
      with:
        command: |
          export CHART_FOLDER=deployment/app-chart
          helm lint $CHART_FOLDER
          helm --namespace $DEPLOYMENT_NAMESPACE upgrade --install --create-namespace $APP_NAME $CHART_FOLDER \
            --set image.tag=$DOCKER_ENV_TAG \
            --set environment.near_env=${NEAR_ENV} \
            --set environment.near_contract_name=${NEAR_CONTRACT_NAME} \
            --set environment.next_public_api_url=${NEXT_PUBLIC_API_URL}
            --set environment.next_public_google_analytics_key=${NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY}
            --set environment.next_public_near_env=${NEXT_PUBLIC_NEAR_ENV}
            --set ingress.host=${K8S_INGRESS_HOST}
