name: Build Deploy
on:
  workflow_dispatch:
  create:
    tags:
    - '*'

jobs:
  build-deploy:
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY: ${{ secrets.NEXT_PUBLIC_GOOGLE_ANALYTICS_KEY }}
      AWS_ECR_URL: ${{ secrets.AWS_ECR_URL }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}
    runs-on: ubuntu-latest
    name: Build Deploy
    environment:
      name: productions
      url: https://${{ secrets.K8S_INGRESS_HOST }}
    steps:
    - uses: actions/checkout@v2
    - name: Set Environment
      run: |
         echo DOCKER_ENV_TAG=production-$GITHUB_SHA >> $GITHUB_ENV
    - name: load env
      run: |
          cat ".github/env.common" >>$GITHUB_ENV
          cat ".github/env.production" >>$GITHUB_ENV

    - name: Build
      uses: ./.github/actions/build

    - name: Docker Build Publish
      uses: ./.github/actions/docker-build-publish

    - name: Helm Deploy
      uses: ./.github/actions/helm-build-deploy
